# Generated by Django 5.2.13 on 2026-04-23 00:17

import apps.intake.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("branches", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Нэр")),
                ("slug", models.SlugField(max_length=100, unique=True, verbose_name="Slug")),
                ("icon", models.CharField(blank=True, max_length=50, verbose_name="Дүрс/Emoji")),
                ("is_active", models.BooleanField(default=True, verbose_name="Идэвхтэй")),
                ("sort_order", models.PositiveIntegerField(default=0, verbose_name="Дараалал")),
            ],
            options={
                "verbose_name": "Төхөөрөмжийн ангилал",
                "verbose_name_plural": "Төхөөрөмжийн ангилалууд",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="DeviceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("brand", models.CharField(blank=True, max_length=100, verbose_name="Бренд")),
                ("model", models.CharField(blank=True, max_length=200, verbose_name="Модель")),
                ("quantity", models.PositiveIntegerField(default=1, verbose_name="Тоо ширхэг")),
                ("storage", models.CharField(blank=True, max_length=50, verbose_name="Багтаамж")),
                ("color", models.CharField(blank=True, max_length=50, verbose_name="Өнгө")),
                (
                    "imei_or_serial",
                    models.CharField(blank=True, max_length=100, verbose_name="IMEI / Сериал"),
                ),
                (
                    "power_on_status",
                    models.CharField(
                        choices=[("YES", "Асна"), ("NO", "Асахгүй"), ("UNKNOWN", "Мэдэхгүй")],
                        default="UNKNOWN",
                        max_length=10,
                        verbose_name="Асах эсэх",
                    ),
                ),
                (
                    "screen_status",
                    models.CharField(
                        choices=[
                            ("OK", "Бүтэн"),
                            ("CRACKED", "Хагарсан"),
                            ("BROKEN", "Эвдэрсэн"),
                            ("DEAD", "Гэрэлтэхгүй"),
                        ],
                        default="OK",
                        max_length=10,
                        verbose_name="Дэлгэцийн төлөв",
                    ),
                ),
                (
                    "battery_status",
                    models.CharField(
                        choices=[
                            ("OK", "Хэвийн"),
                            ("WEAK", "Сул"),
                            ("DEAD", "Үхсэн"),
                            ("UNKNOWN", "Мэдэхгүй"),
                        ],
                        default="UNKNOWN",
                        max_length=10,
                        verbose_name="Батарей",
                    ),
                ),
                (
                    "body_status",
                    models.CharField(
                        choices=[
                            ("OK", "Цэвэр"),
                            ("SCRATCHED", "Зурагдсан"),
                            ("DENTED", "Чөмөгтэй"),
                            ("BROKEN", "Хугарсан"),
                        ],
                        default="OK",
                        max_length=10,
                        verbose_name="Биеийн төлөв",
                    ),
                ),
                ("water_damage", models.BooleanField(default=False, verbose_name="Ус орсон")),
                (
                    "accessories",
                    models.CharField(blank=True, max_length=300, verbose_name="Дагалдах"),
                ),
                (
                    "issue_description",
                    models.TextField(blank=True, verbose_name="Гэмтлийн тайлбар"),
                ),
                (
                    "condition_grade",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A", "A — Маш сайн"),
                            ("B", "B — Сайн"),
                            ("C", "C — Дунд"),
                            ("D", "D — Муу"),
                        ],
                        max_length=2,
                        verbose_name="Үнэлгээний зэрэг",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="intake.devicecategory",
                        verbose_name="Ангилал",
                    ),
                ),
            ],
            options={
                "verbose_name": "Төхөөрөмж",
                "verbose_name_plural": "Төхөөрөмжүүд",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="DeviceImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("image", models.ImageField(upload_to="devices/%Y/%m/", verbose_name="Зураг")),
                ("sort_order", models.PositiveIntegerField(default=0, verbose_name="Дараалал")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "device_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="intake.deviceitem",
                        verbose_name="Төхөөрөмж",
                    ),
                ),
            ],
            options={
                "verbose_name": "Төхөөрөмжийн зураг",
                "verbose_name_plural": "Төхөөрөмжийн зураг",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="IntakeRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "request_code",
                    models.CharField(
                        db_index=True,
                        default=apps.intake.models._gen_request_code,
                        max_length=20,
                        unique=True,
                        verbose_name="Хүсэлтийн код",
                    ),
                ),
                (
                    "tracking_token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "customer_type",
                    models.CharField(
                        choices=[("INDIVIDUAL", "Иргэн"), ("COMPANY", "Компани")],
                        default="INDIVIDUAL",
                        max_length=20,
                        verbose_name="Хэрэглэгчийн төрөл",
                    ),
                ),
                ("contact_name", models.CharField(max_length=200, verbose_name="Холбоо барих нэр")),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=200, verbose_name="Компанийн нэр"),
                ),
                ("contact_phone", models.CharField(max_length=20, verbose_name="Утас")),
                (
                    "contact_email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "city",
                    models.CharField(default="Улаанбаатар", max_length=100, verbose_name="Хот"),
                ),
                ("district", models.CharField(blank=True, max_length=100, verbose_name="Дүүрэг")),
                ("address_line", models.CharField(blank=True, max_length=500, verbose_name="Хаяг")),
                (
                    "expected_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Хүсэж буй үнэ",
                    ),
                ),
                (
                    "pickup_required",
                    models.BooleanField(default=False, verbose_name="Pickup хэрэгтэй"),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("WEB", "Вэб"),
                            ("PHONE_CALL", "Утсаар"),
                            ("FB", "Facebook"),
                            ("WALKIN", "Биеэр"),
                        ],
                        default="WEB",
                        max_length=20,
                        verbose_name="Эх сурвалж",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "Шинэ"),
                            ("UNDER_REVIEW", "Үнэлгээнд"),
                            ("PRICE_SENT", "Үнэ илгээсэн"),
                            ("NEGOTIATING", "Тохиролцож байна"),
                            ("APPROVED", "Зөвшөөрсөн"),
                            ("REJECTED", "Татгалзсан"),
                            ("PURCHASED", "Худалдан авсан"),
                            ("CANCELLED", "Цуцалсан"),
                        ],
                        db_index=True,
                        default="NEW",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Хариуцсан оператор",
                    ),
                ),
                (
                    "preferred_branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="preferred_requests",
                        to="branches.branch",
                        verbose_name="Сонгосон салбар",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitted_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Илгээсэн хэрэглэгч",
                    ),
                ),
            ],
            options={
                "verbose_name": "Хүсэлт",
                "verbose_name_plural": "Хүсэлтүүд",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="deviceitem",
            name="intake_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="intake.intakerequest",
                verbose_name="Хүсэлт",
            ),
        ),
    ]
