# Generated by Django 5.2.13 on 2026-05-31 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intake", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="intakerequest",
            name="source",
            field=models.CharField(
                choices=[
                    ("WEB", "Вэб"),
                    ("APP", "Гар утасны апп"),
                    ("PHONE_CALL", "Утсаар"),
                    ("FB", "Facebook"),
                    ("WALKIN", "Биеэр"),
                ],
                default="WEB",
                max_length=20,
                verbose_name="Эх сурвалж",
            ),
        ),
    ]
