# Generated by Django 5.2.13 on 2026-06-13 15:19

from django.db import migrations, models

# Removed statuses → closest remaining status.
STATUS_MAP = {"UNDER_REVIEW": "NEW", "NEGOTIATING": "PRICE_SENT", "REJECTED": "CANCELLED"}
# Removed body condition → closest remaining one.
BODY_MAP = {"DENTED": "SCRATCHED"}


def remap_forward(apps, schema_editor):
    IntakeRequest = apps.get_model("intake", "IntakeRequest")
    DeviceItem = apps.get_model("intake", "DeviceItem")
    StatusHistory = apps.get_model("quotes", "StatusHistory")
    for old, new in STATUS_MAP.items():
        IntakeRequest.objects.filter(status=old).update(status=new)
        StatusHistory.objects.filter(old_status=old).update(old_status=new)
        StatusHistory.objects.filter(new_status=old).update(new_status=new)
    for old, new in BODY_MAP.items():
        DeviceItem.objects.filter(body_status=old).update(body_status=new)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("intake", "0002_alter_intakerequest_source"),
        ("quotes", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(remap_forward, noop),
        migrations.AlterField(
            model_name="deviceitem",
            name="body_status",
            field=models.CharField(
                choices=[("OK", "Цэвэр"), ("SCRATCHED", "Зурагдсан"), ("BROKEN", "Хугарсан")],
                default="OK",
                max_length=10,
                verbose_name="Биеийн төлөв",
            ),
        ),
        migrations.AlterField(
            model_name="intakerequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("NEW", "Шинэ"),
                    ("PRICE_SENT", "Үнэ илгээсэн"),
                    ("APPROVED", "Зөвшөөрсөн"),
                    ("PURCHASED", "Худалдан авсан"),
                    ("CANCELLED", "Цуцалсан"),
                ],
                db_index=True,
                default="NEW",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
    ]
