# Generated by Django 5.2.13 on 2026-08-06 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intake", "0003_alter_deviceitem_body_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="intakerequest",
            name="pickup_lat",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="Байршил (өргөрөг)",
            ),
        ),
        migrations.AddField(
            model_name="intakerequest",
            name="pickup_lng",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="Байршил (уртраг)",
            ),
        ),
        migrations.AddField(
            model_name="intakerequest",
            name="request_type",
            field=models.CharField(
                choices=[
                    ("WORKING", "Ажиллагаатай утас"),
                    ("BROKEN", "Эвдэрсэн / бусад төхөөрөмж"),
                ],
                default="BROKEN",
                max_length=20,
                verbose_name="Хүсэлтийн төрөл",
            ),
        ),
    ]
