# Generated by Django 5.2.13 on 2026-08-10 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intake", "0005_deactivate_phone_board_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="intakerequest",
            name="images_purge_at",
            field=models.DateTimeField(
                blank=True, db_index=True, null=True, verbose_name="Зураг устгах хугацаа"
            ),
        ),
        migrations.AddField(
            model_name="intakerequest",
            name="images_purged_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Зураг устгасан"),
        ),
    ]
