# Generated by Django 5.2.13 on 2026-06-01 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, verbose_name='Код')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Үүсгэсэн')),
                ('expires_at', models.DateTimeField(verbose_name='Дуусах хугацаа')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Ашигласан')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reset_codes', to=settings.AUTH_USER_MODEL, verbose_name='Хэрэглэгч')),
            ],
            options={
                'verbose_name': 'Нууц үг сэргээх код',
                'verbose_name_plural': 'Нууц үг сэргээх кодууд',
                'ordering': ['-created_at'],
            },
        ),
    ]
