# Generated by Django 5.2.13 on 2026-08-11 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_passwordresetcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address_line',
            field=models.CharField(blank=True, max_length=500, verbose_name='Хаяг'),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Хот'),
        ),
        migrations.AddField(
            model_name='user',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Компанийн нэр'),
        ),
        migrations.AddField(
            model_name='user',
            name='customer_type',
            field=models.CharField(choices=[('INDIVIDUAL', 'Иргэн'), ('COMPANY', 'Компани')], default='INDIVIDUAL', max_length=20, verbose_name='Хэрэглэгчийн төрөл'),
        ),
        migrations.AddField(
            model_name='user',
            name='district',
            field=models.CharField(blank=True, max_length=100, verbose_name='Дүүрэг'),
        ),
    ]
