# Generated by Django 5.2.13 on 2026-08-20 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_address_line_user_city_user_company_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="failed_login_attempts",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="Амжилтгүй оролдлого"),
        ),
        migrations.AddField(
            model_name="user",
            name="locked_until",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Хаалт дуусах"),
        ),
    ]
