# Generated by Django 5.2.13 on 2026-08-20 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_failed_login_attempts_user_locked_until"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="pickup_lat",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="Байршил (өргөрөг)",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="pickup_lng",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="Байршил (уртраг)",
            ),
        ),
    ]
