# Generated by Django 5.2.13 on 2026-06-13 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("key", models.SlugField(max_length=100, unique=True, verbose_name="Түлхүүр")),
                ("title", models.CharField(blank=True, max_length=200, verbose_name="Гарчиг")),
                ("body", models.TextField(blank=True, verbose_name="Агуулга")),
                (
                    "video",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="site/videos/%Y/%m/",
                        verbose_name="Бичлэг (файл)",
                    ),
                ),
                (
                    "video_url",
                    models.URLField(
                        blank=True, max_length=500, verbose_name="Бичлэг (гадаад линк)"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Шинэчилсэн")),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Шинэчилсэн хэрэглэгч",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сайтын агуулга",
                "verbose_name_plural": "Сайтын агуулга",
                "ordering": ["key"],
            },
        ),
    ]
