# Generated by Django 5.2.13 on 2026-08-06 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitecontent",
            name="link_label",
            field=models.CharField(blank=True, max_length=200, verbose_name="Холбоос — нэр"),
        ),
        migrations.AddField(
            model_name="sitecontent",
            name="link_url",
            field=models.URLField(blank=True, max_length=500, verbose_name="Холбоос — URL"),
        ),
    ]
