# Generated by Django 5.2.13 on 2026-04-23 00:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("intake", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Pickup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("pickup_date", models.DateTimeField(verbose_name="Pickup-ийн огноо")),
                ("pickup_address", models.CharField(max_length=500, verbose_name="Pickup хаяг")),
                (
                    "actual_buy_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Бодит худалдан авсан үнэ",
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[("PENDING", "Хүлээгдэж буй"), ("PAID", "Төлөгдсөн")],
                        default="PENDING",
                        max_length=10,
                        verbose_name="Төлбөрийн төлөв",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("CASH", "Бэлэн мөнгө"), ("BANK", "Банк шилжүүлэг")],
                        default="CASH",
                        max_length=10,
                        verbose_name="Төлбөрийн арга",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Тэмдэглэл")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_staff",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pickups",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Хариуцсан ажилтан",
                    ),
                ),
                (
                    "intake_request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pickup",
                        to="intake.intakerequest",
                        verbose_name="Хүсэлт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pickup",
                "verbose_name_plural": "Pickup-үүд",
                "ordering": ["-pickup_date"],
            },
        ),
        migrations.CreateModel(
            name="Quotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "quoted_price_min",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Хамгийн доод үнэ"
                    ),
                ),
                (
                    "quoted_price_max",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Хамгийн дээд үнэ"
                    ),
                ),
                (
                    "final_offer_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Эцсийн санал",
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="Тэмдэглэл")),
                (
                    "valid_until",
                    models.DateField(blank=True, null=True, verbose_name="Хүчинтэй хугацаа"),
                ),
                (
                    "sent_to_customer_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Хэрэглэгчид илгээсэн"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "intake_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quotes",
                        to="intake.intakerequest",
                        verbose_name="Хүсэлт",
                    ),
                ),
                (
                    "quoted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quotations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Үнэлгээ хийсэн",
                    ),
                ),
            ],
            options={
                "verbose_name": "Үнэ санал",
                "verbose_name_plural": "Үнэ саналууд",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "old_status",
                    models.CharField(blank=True, max_length=20, verbose_name="Хуучин статус"),
                ),
                ("new_status", models.CharField(max_length=20, verbose_name="Шинэ статус")),
                ("comment", models.TextField(blank=True, verbose_name="Тайлбар")),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="status_changes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Өөрчилсөн",
                    ),
                ),
                (
                    "intake_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="intake.intakerequest",
                        verbose_name="Хүсэлт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Статусын түүх",
                "verbose_name_plural": "Статусын түүх",
                "ordering": ["-changed_at"],
            },
        ),
    ]
