# Generated by Django 5.2.13 on 2026-04-23 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Нэр")),
                ("code", models.SlugField(blank=True, unique=True, verbose_name="Код")),
                ("address_line", models.CharField(max_length=500, verbose_name="Хаяг")),
                (
                    "city",
                    models.CharField(default="Улаанбаатар", max_length=100, verbose_name="Хот"),
                ),
                ("district", models.CharField(blank=True, max_length=100, verbose_name="Дүүрэг")),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Latitude",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Longitude",
                    ),
                ),
                (
                    "phones",
                    models.JSONField(blank=True, default=list, verbose_name="Утасны жагсаалт"),
                ),
                (
                    "working_hours",
                    models.CharField(
                        default="10:00–17:30", max_length=200, verbose_name="Ажиллах цаг"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Идэвхтэй")),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="branches/covers/%Y/%m/",
                        verbose_name="Нүүр зураг",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Тайлбар")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Салбар",
                "verbose_name_plural": "Салбарууд",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PartnerLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Нэр")),
                (
                    "partner_company",
                    models.CharField(blank=True, max_length=200, verbose_name="Хамтрагч компани"),
                ),
                ("address", models.CharField(max_length=500, verbose_name="Хаяг")),
                ("phone", models.CharField(blank=True, max_length=50, verbose_name="Утас")),
                ("notes", models.TextField(blank=True, verbose_name="Тэмдэглэл")),
                ("is_active", models.BooleanField(default=True, verbose_name="Идэвхтэй")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Хамтрагч цэг",
                "verbose_name_plural": "Хамтрагч цэгүүд",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BranchMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[("IMAGE", "Зураг"), ("VIDEO", "Бичлэг")],
                        default="IMAGE",
                        max_length=10,
                        verbose_name="Төрөл",
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to="branches/gallery/%Y/%m/", verbose_name="Файл"),
                ),
                ("caption", models.CharField(blank=True, max_length=300, verbose_name="Тайлбар")),
                ("sort_order", models.PositiveIntegerField(default=0, verbose_name="Дараалал")),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery",
                        to="branches.branch",
                        verbose_name="Салбар",
                    ),
                ),
            ],
            options={
                "verbose_name": "Салбарын медиа",
                "verbose_name_plural": "Салбарын медиа",
                "ordering": ["sort_order", "id"],
            },
        ),
    ]
