# Generated by Django 5.2.13 on 2026-04-23 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("intake", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("recipient_email", models.EmailField(max_length=254, verbose_name="Хүлээн авагч")),
                ("subject", models.CharField(max_length=300, verbose_name="Гарчиг")),
                (
                    "template_name",
                    models.CharField(blank=True, max_length=100, verbose_name="Template"),
                ),
                (
                    "context_json",
                    models.JSONField(blank=True, default=dict, verbose_name="Context"),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("success", models.BooleanField(default=True)),
                ("error", models.TextField(blank=True, verbose_name="Алдаа")),
                (
                    "intake_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_logs",
                        to="intake.intakerequest",
                        verbose_name="Хүсэлт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email log",
                "verbose_name_plural": "Email logs",
                "ordering": ["-sent_at"],
            },
        ),
    ]
